/**
 * Agent Identity Types — application-level logical agent identifiers.
 *
 * IMPORTANT: These DIDs (did:t3:agent:tact-*) are application-level agent
 * identifiers for this demo. They are NOT real Terminal3-issued tenant DIDs.
 * Real T3N tenant DIDs come from did.value after authenticate().
 */

/** The three logical agent roles in the T.A.C.T pipeline. */
export type AgentRole = "monitor" | "execution" | "reporting";

/** Application-level agent DIDs (demo identifiers, not real T3N tenant DIDs). */
export type AgentDid =
    | "did:t3:agent:tact-monitor"
    | "did:t3:agent:tact-execution"
    | "did:t3:agent:tact-reporting";

/**
 * Audit entry recorded by the agent registry for scope checks,
 * handoffs, and violations.
 */
export interface AgentAuditEntry {
    timestamp: number;
    agentDid: AgentDid;
    role: AgentRole;
    action: string;
    incidentId?: string;
    success: boolean;
    details?: string;
}

/**
 * Payload for creating a validated handoff between two agents.
 */
export interface AgentHandoffPayload {
    sourceAgentDid: AgentDid;
    destinationAgentDid: AgentDid;
    incidentId: string;
    reason: string;
}

/**
 * Record of a validated handoff between agents.
 */
export interface AgentHandoffRecord {
    handoffId: string;
    sourceAgentDid: AgentDid;
    destinationAgentDid: AgentDid;
    incidentId: string;
    reason: string;
    timestamp: number;
}

/**
 * Post-incident report summary generated by the Reporting Agent.
 */
export interface IncidentReportSummary {
    incidentId: string;
    title: string;
    severity: string;
    rootCause: string;
    resolution: string;
    timeline: Array<{ timestamp: number; event: string }>;
    generatedAt: number;
    generatedBy: AgentDid;
}
